title: Panagiotis Moutsiounas - CV
email: p18mout@ionio.gr
description: My Jekyll site where my CV is shown.
baseurl: /cv-1
url: ""
github_username: panagiotismouts

theme: jekyll-theme-cadre
plugins:
      -  jekyll-feed
